version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: andron12/foodgram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - db

  frontend:
    image: andron12/foodgram_frontend
    volumes:
      - static:/app/build/

  gateway:
    image: andron12/foodgram_gateway
    ports:
      - "7000:80"
    volumes:
      - static:/usr/share/nginx/html/
      - media:/usr/share/nginx/media/
    depends_on:
      - backend
      - frontend
