# Generated by Django 3.2.3 on 2023-11-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipesingredients_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients'),
        ),
        migrations.AlterField(
            model_name='recipesingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipes'),
        ),
    ]
